name: testJvm macos

on:
  workflow_dispatch:

jobs:
  jvm-tests:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Run JVM Tests
        run: ./gradlew jvmTest --info --stacktrace